#Gradle
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx2048M"
#Kotlin
kotlin.code.style=official
#kotlin.native.cacheKind=none
#Android
android.useAndroidX=true
#android.enableJetifier=true
#android.nonFinalResIds=false
android.nonTransitiveRClass=true
#android.defaults.buildfeatures.buildconfig=true

# Workaround for AGP 9.x built-in Kotlin sourceSet conflict
android.builtInKotlin=false
android.newDsl=false
