name: Android Publish Build

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Setup release keystore
        run: |
          echo "${{ secrets.STORE_FILE_BODY }}" > release.keystore.jks

      - name: Create local.properties
        run: |
          echo "prop1=${{ secrets.ADMOB_UNIT_ID }}" > local.properties
          echo "prop2=${{ secrets.ADMOB_TEST_DEVICE_ID }}" >> local.properties
          echo "prop3=${{ secrets.STORE_PASSWORD }}" >> local.properties
          echo "prop4=${{ secrets.KEY_PASSWORD }}" >> local.properties
          echo "prop5=${{ secrets.KEY_ALIAS }}" >> local.properties
          echo "prop6=${{ secrets.STORE_FILE_NAME }}" >> local.properties          

      - name: Gradle Release Assemble
        uses: gradle/gradle-build-action@v2
      - name: Build Release app
        run: ./gradlew assembleRelease

      - name: Deploy to Google Play Store
        uses: actions/google-play-deploy@v1
        with:
          service-account-key: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_KEY }}
          apk-files: app/build/outputs/apk/release/*.apk
          track: production