name: Android Release Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Setup release keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: release.keystore
          encodedString: ${{ secrets.STORE_FILE_BODY }}

      - name: Create local.properties
        run: |
          echo "admobUnitId=${{ secrets.ADMOB_UNIT_ID }}" > local.properties
          echo "admobTestDeviceId=${{ secrets.ADMOB_TEST_DEVICE_ID }}" >> local.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> local.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> local.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> local.properties
          echo "storeFileName=${{ secrets.STORE_FILE_NAME }}" >> local.properties

      - name: Verify keystore file exists
        run: |
          ls -la          

      - name: Gradle Release Assemble
        uses: gradle/gradle-build-action@v2
      - name: Build Release app
        run: ./gradlew assembleRelease

      - name: Unit Test
        run: ./gradlew testReleaseUnitTest

      - name: Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}